// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebApplication4.Daten;

namespace WebApplication4.Migrations
{
    [DbContext(typeof(LolocoContext))]
    [Migration("20171220155525_one")]
    partial class one
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication4.Models.Consumer", b =>
                {
                    b.Property<int>("Consumerid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.HasKey("Consumerid");

                    b.ToTable("Consumer");
                });

            modelBuilder.Entity("WebApplication4.Models.Ha", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EnrollmentDate");

                    b.Property<string>("FirstMidName");

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.ToTable("Has");
                });

            modelBuilder.Entity("WebApplication4.Models.Trader", b =>
                {
                    b.Property<int>("TraderID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birtday");

                    b.Property<int?>("Consumerid");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("TraderID");

                    b.HasIndex("Consumerid");

                    b.ToTable("Ha");
                });

            modelBuilder.Entity("WebApplication4.Models.Trader", b =>
                {
                    b.HasOne("WebApplication4.Models.Consumer", "Consumer")
                        .WithMany("Traders")
                        .HasForeignKey("Consumerid");
                });
#pragma warning restore 612, 618
        }
    }
}
